banner = 'Welcome to bastion server, {username}!'
port = 8022

[passwords]
admin-1 = 'qV2iEadIGV2rw' # password of 'secretpw'
dev-user1 = '' # do not need password
test-user1 = ''


[[hosts]]
name = 'test-server'
hostname = 'xxx.xxx.xxx.xxx'
username = 'ubuntu'
sshkey = 'keyname'

[[hosts]]
name = 'dev-server'
hostname = 'xxx.xxx.xxx.xxx'
username = 'ubuntu'
sshkey = 'keyname'

[[groups]]
name = 'admin'
users = ['admin-1', 'admin-2']

[[groups]]
name = 'dev'
users = ['dev-user1', 'dev-user2']

[[groups]]
name = 'test'
users = ['test-user1', 'test-user2', 'test-user3']

[[permissions]]
groups = ['admin']
hostnames = ['.*']

[[permissions]]
groups = ['dev']
hostnames = ['^dev.*$']

[[permissions]]
groups = ['test']
hostnames = ['^test.*$']
